<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260409025419 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activite CHANGE description description LONGTEXT DEFAULT NULL, CHANGE prix prix DOUBLE PRECISION DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT \'DISPONIBLE\' NOT NULL');
        $this->addSql('ALTER TABLE activite ADD CONSTRAINT FK_B8755515D7ED1D4B FOREIGN KEY (guide_id) REFERENCES guide (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activite ADD CONSTRAINT FK_B8755515816C6140 FOREIGN KEY (destination_id) REFERENCES ville (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX guide_id ON activite');
        $this->addSql('CREATE INDEX IDX_B8755515D7ED1D4B ON activite (guide_id)');
        $this->addSql('DROP INDEX fk_activite_ville ON activite');
        $this->addSql('CREATE INDEX IDX_B8755515816C6140 ON activite (destination_id)');
        $this->addSql('ALTER TABLE attraction DROP FOREIGN KEY `attraction_ibfk_1`');
        $this->addSql('ALTER TABLE attraction CHANGE id id INT NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE prix prix DOUBLE PRECISION NOT NULL, CHANGE ville_id ville_id INT DEFAULT NULL, CHANGE heure_ouverture heure_ouverture VARCHAR(255) NOT NULL, CHANGE heure_fermeture heure_fermeture VARCHAR(255) NOT NULL, CHANGE est_ferme est_ferme TINYINT NOT NULL');
        $this->addSql('DROP INDEX ville_id ON attraction');
        $this->addSql('CREATE INDEX IDX_D503E6B8A73F0036 ON attraction (ville_id)');
        $this->addSql('ALTER TABLE attraction ADD CONSTRAINT `attraction_ibfk_1` FOREIGN KEY (ville_id) REFERENCES ville (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE avis DROP FOREIGN KEY `avis_ibfk_1`');
        $this->addSql('ALTER TABLE avis DROP FOREIGN KEY `avis_ibfk_2`');
        $this->addSql('ALTER TABLE avis CHANGE note note INT NOT NULL, CHANGE commentaire commentaire LONGTEXT NOT NULL, CHANGE dateAvis dateAvis DATETIME NOT NULL, CHANGE activite_id activite_id INT NOT NULL, CHANGE personne_id personne_id INT NOT NULL');
        $this->addSql('DROP INDEX activite_id ON avis');
        $this->addSql('CREATE INDEX IDX_8F91ABF09B0F88B1 ON avis (activite_id)');
        $this->addSql('DROP INDEX personne_id ON avis');
        $this->addSql('CREATE INDEX IDX_8F91ABF0A21BD112 ON avis (personne_id)');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT `avis_ibfk_1` FOREIGN KEY (activite_id) REFERENCES activite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT `avis_ibfk_2` FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY `commentaire_ibfk_1`');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY `commentaire_ibfk_2`');
        $this->addSql('ALTER TABLE commentaire ADD date_commentaire DATETIME NOT NULL, DROP dateCommentaire, CHANGE id id INT NOT NULL, CHANGE contenu contenu LONGTEXT NOT NULL');
        $this->addSql('DROP INDEX personne_id ON commentaire');
        $this->addSql('CREATE INDEX IDX_67F068BCA21BD112 ON commentaire (personne_id)');
        $this->addSql('DROP INDEX post_id ON commentaire');
        $this->addSql('CREATE INDEX IDX_67F068BC4B89032C ON commentaire (post_id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT `commentaire_ibfk_1` FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT `commentaire_ibfk_2` FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE user1_id user1_id INT DEFAULT NULL, CHANGE user2_id user2_id INT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E956AE248B FOREIGN KEY (user1_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9441B8B65 FOREIGN KEY (user2_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_8A8E26E956AE248B ON conversation (user1_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E9441B8B65 ON conversation (user2_id)');
        $this->addSql('ALTER TABLE favoris DROP INDEX personne_id, ADD INDEX IDX_8933C432A21BD112 (personne_id)');
        $this->addSql('ALTER TABLE favoris ADD date_creation DATETIME NOT NULL, DROP dateCreation, CHANGE id id INT NOT NULL, CHANGE personne_id personne_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE favoris_post DROP FOREIGN KEY `favoris_post_ibfk_2`');
        $this->addSql('ALTER TABLE favoris_post ADD date_ajout DATETIME NOT NULL, DROP dateAjout');
        $this->addSql('DROP INDEX post_id ON favoris_post');
        $this->addSql('CREATE INDEX IDX_E90DF6EA4B89032C ON favoris_post (post_id)');
        $this->addSql('ALTER TABLE favoris_post ADD CONSTRAINT `favoris_post_ibfk_2` FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE guide DROP FOREIGN KEY `fk_guide_personne`');
        $this->addSql('ALTER TABLE guide CHANGE specialite specialite VARCHAR(150) NOT NULL, CHANGE langues langues VARCHAR(250) NOT NULL, CHANGE experience experience VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE likes DROP FOREIGN KEY `likes_ibfk_1`');
        $this->addSql('ALTER TABLE likes DROP FOREIGN KEY `likes_ibfk_2`');
        $this->addSql('ALTER TABLE likes CHANGE id id INT NOT NULL, CHANGE statut statut TINYINT NOT NULL');
        $this->addSql('DROP INDEX personne_id ON likes');
        $this->addSql('CREATE INDEX IDX_49CA4E7DA21BD112 ON likes (personne_id)');
        $this->addSql('DROP INDEX post_id ON likes');
        $this->addSql('CREATE INDEX IDX_49CA4E7D4B89032C ON likes (post_id)');
        $this->addSql('ALTER TABLE likes ADD CONSTRAINT `likes_ibfk_1` FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE likes ADD CONSTRAINT `likes_ibfk_2` FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE conversation_id conversation_id INT DEFAULT NULL, CHANGE sender_id sender_id INT DEFAULT NULL, CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE sent_at sent_at DATETIME NOT NULL, CHANGE is_read is_read TINYINT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `fk_notification_activite`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `fk_notif_comment`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `fk_notif_post`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `fk_notif_receiver`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `fk_notif_sender`');
        $this->addSql('ALTER TABLE notification CHANGE id id INT NOT NULL, CHANGE message message LONGTEXT NOT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE is_read is_read TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE is_sent_sms is_sent_sms TINYINT NOT NULL');
        $this->addSql('DROP INDEX fk_notif_post ON notification');
        $this->addSql('CREATE INDEX IDX_BF5476CA4B89032C ON notification (post_id)');
        $this->addSql('DROP INDEX fk_notif_comment ON notification');
        $this->addSql('CREATE INDEX IDX_BF5476CAF8697D13 ON notification (comment_id)');
        $this->addSql('DROP INDEX idx_notification_activite_id ON notification');
        $this->addSql('CREATE INDEX IDX_BF5476CA9B0F88B1 ON notification (activite_id)');
        $this->addSql('DROP INDEX fk_notif_sender ON notification');
        $this->addSql('CREATE INDEX IDX_BF5476CAF624B39D ON notification (sender_id)');
        $this->addSql('DROP INDEX fk_notif_receiver ON notification');
        $this->addSql('CREATE INDEX IDX_BF5476CACD53EDB6 ON notification (receiver_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `fk_notification_activite` FOREIGN KEY (activite_id) REFERENCES activite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `fk_notif_comment` FOREIGN KEY (comment_id) REFERENCES commentaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `fk_notif_post` FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `fk_notif_receiver` FOREIGN KEY (receiver_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `fk_notif_sender` FOREIGN KEY (sender_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pays CHANGE id id INT NOT NULL, CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE visit_count visit_count INT NOT NULL');
        $this->addSql('DROP INDEX email ON personne');
        $this->addSql('ALTER TABLE personne CHANGE id id INT NOT NULL, CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE prenom prenom VARCHAR(100) NOT NULL, CHANGE email email VARCHAR(150) NOT NULL, CHANGE motDePasse motDePasse VARCHAR(255) NOT NULL, CHANGE dateInscription dateInscription DATE NOT NULL, CHANGE role role VARCHAR(255) NOT NULL, CHANGE statutCompte statutCompte enum(\'ACTIF\', \'INACTIF\', \'SUSPENDU\'), CHANGE telephone telephone VARCHAR(20) NOT NULL, CHANGE notifSmsActive notifSmsActive TINYINT NOT NULL, CHANGE profile_photo profile_photo VARCHAR(500) NOT NULL');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY `post_ibfk_1`');
        $this->addSql('ALTER TABLE post CHANGE titre titre VARCHAR(150) NOT NULL, CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE datePublication datePublication DATETIME NOT NULL, CHANGE popularite popularite INT NOT NULL');
        $this->addSql('DROP INDEX personne_id ON post');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DA21BD112 ON post (personne_id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT `post_ibfk_1` FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE preference DROP INDEX personne_id, ADD INDEX IDX_5D69B053A21BD112 (personne_id)');
        $this->addSql('ALTER TABLE preference ADD budget_min DOUBLE PRECISION NOT NULL, ADD budget_max DOUBLE PRECISION NOT NULL, ADD types_voyage LONGTEXT NOT NULL, ADD centres_interet LONGTEXT NOT NULL, DROP budgetMin, DROP budgetMax, DROP typesVoyage, DROP centresInteret, CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY `reservation_ibfk_1`');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY `reservation_ibfk_2`');
        $this->addSql('ALTER TABLE reservation ADD date_reservation DATE NOT NULL, ADD date_debut DATE NOT NULL, ADD date_fin DATE NOT NULL, ADD cout_total DOUBLE PRECISION NOT NULL, DROP dateReservation, DROP dateDebut, DROP dateFin, DROP coutTotal, CHANGE id id INT NOT NULL, CHANGE statut statut VARCHAR(50) NOT NULL, CHANGE nb_tickets nb_tickets INT NOT NULL');
        $this->addSql('DROP INDEX personne_id ON reservation');
        $this->addSql('CREATE INDEX IDX_42C84955A21BD112 ON reservation (personne_id)');
        $this->addSql('DROP INDEX destination_id ON reservation');
        $this->addSql('CREATE INDEX IDX_42C84955816C6140 ON reservation (destination_id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT `reservation_ibfk_1` FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT `reservation_ibfk_2` FOREIGN KEY (destination_id) REFERENCES pays (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY `fk_ticket_activite`');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY `fk_ticket_destination`');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY `fk_ticket_activite`');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY `fk_ticket_destination`');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY `ticket_ibfk_1`');
        $this->addSql('ALTER TABLE ticket CHANGE type type VARCHAR(100) NOT NULL, CHANGE dateDebut dateDebut DATE NOT NULL, CHANGE dateFin dateFin DATE NOT NULL, CHANGE statut statut VARCHAR(50) DEFAULT \'Disponible\' NOT NULL, CHANGE prix prix DOUBLE PRECISION NOT NULL');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3816C6140 FOREIGN KEY (destination_id) REFERENCES ville (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA39B0F88B1 FOREIGN KEY (activite_id) REFERENCES activite (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX reservation_id ON ticket');
        $this->addSql('CREATE INDEX IDX_97A0ADA3B83297E7 ON ticket (reservation_id)');
        $this->addSql('DROP INDEX fk_ticket_destination ON ticket');
        $this->addSql('CREATE INDEX IDX_97A0ADA3816C6140 ON ticket (destination_id)');
        $this->addSql('DROP INDEX fk_ticket_activite ON ticket');
        $this->addSql('CREATE INDEX IDX_97A0ADA39B0F88B1 ON ticket (activite_id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT `fk_ticket_activite` FOREIGN KEY (activite_id) REFERENCES activite (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT `fk_ticket_destination` FOREIGN KEY (destination_id) REFERENCES pays (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT `ticket_ibfk_1` FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ville DROP FOREIGN KEY `ville_ibfk_1`');
        $this->addSql('ALTER TABLE ville CHANGE id id INT NOT NULL, CHANGE pays_id pays_id INT DEFAULT NULL, CHANGE visit_count visit_count INT NOT NULL, CHANGE latitude latitude DOUBLE PRECISION NOT NULL, CHANGE longitude longitude DOUBLE PRECISION NOT NULL, CHANGE typeTourisme typeTourisme VARCHAR(255) NOT NULL, CHANGE saison saison VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX pays_id ON ville');
        $this->addSql('CREATE INDEX IDX_43C3D9C3A6E44244 ON ville (pays_id)');
        $this->addSql('ALTER TABLE ville ADD CONSTRAINT `ville_ibfk_1` FOREIGN KEY (pays_id) REFERENCES pays (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_waitlist_next ON waitlist');
        $this->addSql('DROP INDEX uq_waitlist_unique ON waitlist');
        $this->addSql('DROP INDEX uq_waitlist_token ON waitlist');
        $this->addSql('DROP INDEX idx_waitlist_pick ON waitlist');
        $this->addSql('DROP INDEX uq_waitlist_user_activity ON waitlist');
        $this->addSql('ALTER TABLE waitlist DROP FOREIGN KEY `fk_waitlist_personne`');
        $this->addSql('ALTER TABLE waitlist CHANGE id id INT NOT NULL, CHANGE activite_id activite_id INT DEFAULT NULL, CHANGE personne_id personne_id INT DEFAULT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE hold_expires_at hold_expires_at DATETIME NOT NULL, CHANGE hold_token hold_token VARCHAR(64) NOT NULL');
        $this->addSql('DROP INDEX fk_waitlist_personne ON waitlist');
        $this->addSql('CREATE INDEX IDX_A8533F28A21BD112 ON waitlist (personne_id)');
        $this->addSql('ALTER TABLE waitlist ADD CONSTRAINT `fk_waitlist_personne` FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activite DROP FOREIGN KEY FK_B8755515D7ED1D4B');
        $this->addSql('ALTER TABLE activite DROP FOREIGN KEY FK_B8755515816C6140');
        $this->addSql('ALTER TABLE activite DROP FOREIGN KEY FK_B8755515D7ED1D4B');
        $this->addSql('ALTER TABLE activite DROP FOREIGN KEY FK_B8755515816C6140');
        $this->addSql('ALTER TABLE activite CHANGE description description TEXT DEFAULT NULL, CHANGE prix prix NUMERIC(10, 2) DEFAULT NULL, CHANGE status status ENUM(\'DISPONIBLE\', \'INDISPONIBLE\') DEFAULT \'DISPONIBLE\' NOT NULL');
        $this->addSql('DROP INDEX idx_b8755515d7ed1d4b ON activite');
        $this->addSql('CREATE INDEX guide_id ON activite (guide_id)');
        $this->addSql('DROP INDEX idx_b8755515816c6140 ON activite');
        $this->addSql('CREATE INDEX fk_activite_ville ON activite (destination_id)');
        $this->addSql('ALTER TABLE activite ADD CONSTRAINT FK_B8755515D7ED1D4B FOREIGN KEY (guide_id) REFERENCES guide (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activite ADD CONSTRAINT FK_B8755515816C6140 FOREIGN KEY (destination_id) REFERENCES ville (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE attraction DROP FOREIGN KEY FK_D503E6B8A73F0036');
        $this->addSql('ALTER TABLE attraction CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE type type LONGTEXT NOT NULL, CHANGE prix prix NUMERIC(10, 2) DEFAULT \'0.00\', CHANGE heure_ouverture heure_ouverture TIME DEFAULT NULL, CHANGE heure_fermeture heure_fermeture TIME DEFAULT NULL, CHANGE est_ferme est_ferme TINYINT DEFAULT NULL, CHANGE ville_id ville_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_d503e6b8a73f0036 ON attraction');
        $this->addSql('CREATE INDEX ville_id ON attraction (ville_id)');
        $this->addSql('ALTER TABLE attraction ADD CONSTRAINT FK_D503E6B8A73F0036 FOREIGN KEY (ville_id) REFERENCES ville (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE avis DROP FOREIGN KEY FK_8F91ABF09B0F88B1');
        $this->addSql('ALTER TABLE avis DROP FOREIGN KEY FK_8F91ABF0A21BD112');
        $this->addSql('ALTER TABLE avis CHANGE note note INT DEFAULT NULL, CHANGE commentaire commentaire TEXT DEFAULT NULL, CHANGE dateAvis dateAvis DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE activite_id activite_id INT DEFAULT NULL, CHANGE personne_id personne_id INT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_8f91abf0a21bd112 ON avis');
        $this->addSql('CREATE INDEX personne_id ON avis (personne_id)');
        $this->addSql('DROP INDEX idx_8f91abf09b0f88b1 ON avis');
        $this->addSql('CREATE INDEX activite_id ON avis (activite_id)');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF09B0F88B1 FOREIGN KEY (activite_id) REFERENCES activite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0A21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BCA21BD112');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BC4B89032C');
        $this->addSql('ALTER TABLE commentaire ADD dateCommentaire DATETIME DEFAULT CURRENT_TIMESTAMP, DROP date_commentaire, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE contenu contenu TEXT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_67f068bc4b89032c ON commentaire');
        $this->addSql('CREATE INDEX post_id ON commentaire (post_id)');
        $this->addSql('DROP INDEX idx_67f068bca21bd112 ON commentaire');
        $this->addSql('CREATE INDEX personne_id ON commentaire (personne_id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCA21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E956AE248B');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E9441B8B65');
        $this->addSql('DROP INDEX IDX_8A8E26E956AE248B ON conversation');
        $this->addSql('DROP INDEX IDX_8A8E26E9441B8B65 ON conversation');
        $this->addSql('ALTER TABLE conversation MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE conversation CHANGE id id INT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE user1_id user1_id INT NOT NULL, CHANGE user2_id user2_id INT NOT NULL, DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE favoris DROP INDEX IDX_8933C432A21BD112, ADD UNIQUE INDEX personne_id (personne_id)');
        $this->addSql('ALTER TABLE favoris ADD dateCreation DATETIME DEFAULT CURRENT_TIMESTAMP, DROP date_creation, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE personne_id personne_id INT NOT NULL');
        $this->addSql('ALTER TABLE favoris_post DROP FOREIGN KEY FK_E90DF6EA4B89032C');
        $this->addSql('ALTER TABLE favoris_post ADD dateAjout DATETIME DEFAULT CURRENT_TIMESTAMP, DROP date_ajout');
        $this->addSql('DROP INDEX idx_e90df6ea4b89032c ON favoris_post');
        $this->addSql('CREATE INDEX post_id ON favoris_post (post_id)');
        $this->addSql('ALTER TABLE favoris_post ADD CONSTRAINT FK_E90DF6EA4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE guide CHANGE specialite specialite VARCHAR(150) DEFAULT NULL, CHANGE langues langues VARCHAR(250) DEFAULT NULL, CHANGE experience experience FLOAT DEFAULT NULL');
        $this->addSql('ALTER TABLE guide ADD CONSTRAINT `fk_guide_personne` FOREIGN KEY (id) REFERENCES personne (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE likes DROP FOREIGN KEY FK_49CA4E7DA21BD112');
        $this->addSql('ALTER TABLE likes DROP FOREIGN KEY FK_49CA4E7D4B89032C');
        $this->addSql('ALTER TABLE likes CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE statut statut TINYINT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_49ca4e7d4b89032c ON likes');
        $this->addSql('CREATE INDEX post_id ON likes (post_id)');
        $this->addSql('DROP INDEX idx_49ca4e7da21bd112 ON likes');
        $this->addSql('CREATE INDEX personne_id ON likes (personne_id)');
        $this->addSql('ALTER TABLE likes ADD CONSTRAINT FK_49CA4E7DA21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE likes ADD CONSTRAINT FK_49CA4E7D4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF624B39D');
        $this->addSql('DROP INDEX IDX_B6BD307F9AC0396 ON message');
        $this->addSql('DROP INDEX IDX_B6BD307FF624B39D ON message');
        $this->addSql('ALTER TABLE message MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE message CHANGE id id INT NOT NULL, CHANGE contenu contenu TEXT DEFAULT NULL, CHANGE sent_at sent_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE is_read is_read TINYINT DEFAULT 0, CHANGE conversation_id conversation_id INT NOT NULL, CHANGE sender_id sender_id INT NOT NULL, DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA4B89032C');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAF8697D13');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA9B0F88B1');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAF624B39D');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CACD53EDB6');
        $this->addSql('ALTER TABLE notification CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE message message TEXT NOT NULL, CHANGE type type ENUM(\'POST\', \'LIKE\', \'COMMENT\', \'WAITLIST_HOLD\', \'WAITLIST_CONFIRMED\', \'BOOKING_CONFIRMED\', \'BOOKING_CANCELLED\') NOT NULL, CHANGE is_read is_read TINYINT DEFAULT 0, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE is_sent_sms is_sent_sms TINYINT DEFAULT 0');
        $this->addSql('DROP INDEX idx_bf5476caf624b39d ON notification');
        $this->addSql('CREATE INDEX fk_notif_sender ON notification (sender_id)');
        $this->addSql('DROP INDEX idx_bf5476cacd53edb6 ON notification');
        $this->addSql('CREATE INDEX fk_notif_receiver ON notification (receiver_id)');
        $this->addSql('DROP INDEX idx_bf5476ca4b89032c ON notification');
        $this->addSql('CREATE INDEX fk_notif_post ON notification (post_id)');
        $this->addSql('DROP INDEX idx_bf5476ca9b0f88b1 ON notification');
        $this->addSql('CREATE INDEX idx_notification_activite_id ON notification (activite_id)');
        $this->addSql('DROP INDEX idx_bf5476caf8697d13 ON notification');
        $this->addSql('CREATE INDEX fk_notif_comment ON notification (comment_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAF8697D13 FOREIGN KEY (comment_id) REFERENCES commentaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA9B0F88B1 FOREIGN KEY (activite_id) REFERENCES activite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAF624B39D FOREIGN KEY (sender_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CACD53EDB6 FOREIGN KEY (receiver_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pays CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nom nom VARCHAR(100) DEFAULT NULL, CHANGE description description TEXT NOT NULL, CHANGE visit_count visit_count INT DEFAULT 0');
        $this->addSql('ALTER TABLE personne CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nom nom VARCHAR(100) DEFAULT NULL, CHANGE prenom prenom VARCHAR(100) DEFAULT NULL, CHANGE email email VARCHAR(150) DEFAULT NULL, CHANGE motDePasse motDePasse VARCHAR(255) DEFAULT NULL, CHANGE dateInscription dateInscription DATE DEFAULT NULL, CHANGE role role ENUM(\'CLIENT\', \'GUIDE\', \'ADMIN\') NOT NULL, CHANGE statutCompte statutCompte ENUM(\'ACTIF\', \'INACTIF\', \'SUSPENDU\') DEFAULT \'ACTIF\', CHANGE telephone telephone VARCHAR(20) DEFAULT NULL, CHANGE notifSmsActive notifSmsActive TINYINT DEFAULT 1, CHANGE profile_photo profile_photo VARCHAR(500) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX email ON personne (email)');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DA21BD112');
        $this->addSql('ALTER TABLE post CHANGE titre titre VARCHAR(150) DEFAULT NULL, CHANGE contenu contenu TEXT DEFAULT NULL, CHANGE datePublication datePublication DATETIME DEFAULT NULL, CHANGE popularite popularite INT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_5a8a6c8da21bd112 ON post');
        $this->addSql('CREATE INDEX personne_id ON post (personne_id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DA21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE preference DROP INDEX IDX_5D69B053A21BD112, ADD UNIQUE INDEX personne_id (personne_id)');
        $this->addSql('ALTER TABLE preference ADD budgetMin DOUBLE PRECISION DEFAULT NULL, ADD budgetMax DOUBLE PRECISION DEFAULT NULL, ADD typesVoyage TEXT DEFAULT NULL, ADD centresInteret TEXT DEFAULT NULL, DROP budget_min, DROP budget_max, DROP types_voyage, DROP centres_interet, CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955A21BD112');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955816C6140');
        $this->addSql('ALTER TABLE reservation ADD dateReservation DATE DEFAULT NULL, ADD dateDebut DATE DEFAULT NULL, ADD dateFin DATE DEFAULT NULL, ADD coutTotal DOUBLE PRECISION DEFAULT NULL, DROP date_reservation, DROP date_debut, DROP date_fin, DROP cout_total, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE statut statut VARCHAR(50) DEFAULT NULL, CHANGE nb_tickets nb_tickets INT DEFAULT 0 NOT NULL');
        $this->addSql('DROP INDEX idx_42c84955a21bd112 ON reservation');
        $this->addSql('CREATE INDEX personne_id ON reservation (personne_id)');
        $this->addSql('DROP INDEX idx_42c84955816c6140 ON reservation');
        $this->addSql('CREATE INDEX destination_id ON reservation (destination_id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955816C6140 FOREIGN KEY (destination_id) REFERENCES pays (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3816C6140');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA39B0F88B1');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3B83297E7');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3816C6140');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA39B0F88B1');
        $this->addSql('ALTER TABLE ticket CHANGE type type VARCHAR(100) DEFAULT NULL, CHANGE dateDebut dateDebut DATE DEFAULT NULL, CHANGE dateFin dateFin DATE DEFAULT NULL, CHANGE statut statut VARCHAR(50) DEFAULT NULL, CHANGE prix prix DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT `fk_ticket_activite` FOREIGN KEY (activite_id) REFERENCES activite (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT `fk_ticket_destination` FOREIGN KEY (destination_id) REFERENCES pays (id)');
        $this->addSql('DROP INDEX idx_97a0ada39b0f88b1 ON ticket');
        $this->addSql('CREATE INDEX fk_ticket_activite ON ticket (activite_id)');
        $this->addSql('DROP INDEX idx_97a0ada3b83297e7 ON ticket');
        $this->addSql('CREATE INDEX reservation_id ON ticket (reservation_id)');
        $this->addSql('DROP INDEX idx_97a0ada3816c6140 ON ticket');
        $this->addSql('CREATE INDEX fk_ticket_destination ON ticket (destination_id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3816C6140 FOREIGN KEY (destination_id) REFERENCES ville (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA39B0F88B1 FOREIGN KEY (activite_id) REFERENCES activite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ville DROP FOREIGN KEY FK_43C3D9C3A6E44244');
        $this->addSql('ALTER TABLE ville CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE visit_count visit_count INT DEFAULT 0, CHANGE latitude latitude DOUBLE PRECISION DEFAULT \'0\', CHANGE longitude longitude DOUBLE PRECISION DEFAULT \'0\', CHANGE typeTourisme typeTourisme LONGTEXT NOT NULL, CHANGE saison saison ENUM(\'Winter\', \'Spring\', \'Summer\', \'Autumn\', \'All Year\') NOT NULL, CHANGE pays_id pays_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_43c3d9c3a6e44244 ON ville');
        $this->addSql('CREATE INDEX pays_id ON ville (pays_id)');
        $this->addSql('ALTER TABLE ville ADD CONSTRAINT FK_43C3D9C3A6E44244 FOREIGN KEY (pays_id) REFERENCES pays (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE waitlist DROP FOREIGN KEY FK_A8533F28A21BD112');
        $this->addSql('ALTER TABLE waitlist CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE status status ENUM(\'WAITING\', \'HOLD\', \'CONFIRMED\', \'EXPIRED\', \'CANCELLED\') DEFAULT \'WAITING\' NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE hold_expires_at hold_expires_at DATETIME DEFAULT NULL, CHANGE hold_token hold_token VARCHAR(64) DEFAULT NULL, CHANGE activite_id activite_id INT NOT NULL, CHANGE personne_id personne_id INT NOT NULL');
        $this->addSql('CREATE INDEX idx_waitlist_next ON waitlist (activite_id, status, created_at)');
        $this->addSql('CREATE UNIQUE INDEX uq_waitlist_unique ON waitlist (activite_id, personne_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_waitlist_token ON waitlist (hold_token)');
        $this->addSql('CREATE INDEX idx_waitlist_pick ON waitlist (activite_id, status, created_at)');
        $this->addSql('CREATE UNIQUE INDEX uq_waitlist_user_activity ON waitlist (activite_id, personne_id)');
        $this->addSql('DROP INDEX idx_a8533f28a21bd112 ON waitlist');
        $this->addSql('CREATE INDEX fk_waitlist_personne ON waitlist (personne_id)');
        $this->addSql('ALTER TABLE waitlist ADD CONSTRAINT FK_A8533F28A21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE');
    }
}
