controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_avatar_bundle:
    resource:
        path: ../src/UserAvatarBundle/Controller/
        namespace: App\UserAvatarBundle\Controller
    type: attribute

tattali_calendar:
    resource: "@CalendarBundle/Resources/config/routing.yaml"