# config/services.yaml

parameters:
    activities_directory: '%kernel.project_dir%/public/uploads/activities'
    images_directory: '%kernel.project_dir%/public/uploads'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    openrouter_api_key: '%env(OPENROUTER_API_KEY)%'
    recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha_secret_key: '%env(RECAPTCHA_SECRET_KEY)%'
    recaptcha_v2_site_key: '%env(RECAPTCHA_V2_SITE_KEY)%'
    recaptcha_v2_secret_key: '%env(RECAPTCHA_V2_SECRET_KEY)%'

    mistral_api_key: '%env(MISTRAL_API_KEY)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true 
        
   
   

    # default configuration for services in *this* file
    

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CloudinaryService:
        public: true

    App\Service\AyrshareService:
        public: true

    App\Service\UserRiskAnalysisService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'
            $geminiApiKey2: '%env(GEMINI_API_KEY2)%'
            $openRouterApiKey: '%env(OPENROUTER_API_KEY)%'

    App\UserMailerBundle\Service\UserMailerService:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\PaymentController:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    App\Service\AiDescriptionService:
        arguments:
            $openRouterApiKey: '%openrouter_api_key%'


    App\SmsBundle\Service\SmsSender:
        arguments:
            $sid: '%env(TWILIO_SID)%'
            $token: '%env(TWILIO_TOKEN)%'
            $from: '%env(TWILIO_FROM)%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
# config/services.yaml

    

    App\Service\MistralRecommendationService:
        arguments:
            $mistralApiKey: '%mistral_api_key%'