# config/services.yaml

parameters:
    activities_directory: '%kernel.project_dir%/public/uploads/activities'
    images_directory: '%kernel.project_dir%/public/uploads'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    openrouter_api_key: '%env(OPENROUTER_API_KEY)%'
    mistral_api_key: '%env(MISTRAL_API_KEY)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CloudinaryService:
        public: true

    App\Service\AyrshareService:
        public: true

    App\Controller\PaymentController:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    App\Service\AiDescriptionService:
        arguments:
            $openRouterApiKey: '%openrouter_api_key%'

    App\Service\MistralRecommendationService:
        arguments:
            $mistralApiKey: '%mistral_api_key%'